spring:
  application:
    name: speaker-reminders
  mail:
    host: ${MAIL-HOST}
    port: ${MAIL-PORT}
    username: ${MAIL-USERNAME}
    password: ${MAIL-PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: ${MAIL-PROTOCOL}
  batch:
    job:
      enabled: false
  main:
    allow-bean-definition-overriding: true

google:
  sheet: ${GSHEET-BOOK}
  speaker-sheet: ${GSHEET-SPEAKER}

email:
  from: ${EMAIL-FROM}
  cc: ${EMAIL-CC}
