spring:
  application:
    name: speaker-reminders
  mail:
    host: ${MAIL-HOST}
    port: ${MAIL-PORT}
    username: ${MAIL-USERNAME}
    password: ${MAIL-PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: ${MAIL-PROTOCOL}
  batch:
    job:
      enabled: false
  main:
    allow-bean-definition-overriding: true

  mvc:
    servlet:
      path: /api

google:
  sheet: ${GSHEET-BOOK}
  speaker-sheet: ${GSHEET-SPEAKER}

email:
  from: ${EMAIL-FROM}
  cc: ${EMAIL-CC}

cron:
  schedule: ${CRON-EXPRESSION}

whatsapp:
  url: ${WHATSAPP_URL}
  template: ${WHATSAPP_TEMPLATE}
  token: ${WHATSAPP_TOKEN}
  phoneNumberId: ${WHATSAPP_PHONE_NUMBER_ID}
  toPhoneNumber: ${WHATSAPP_TO_PHONE_NUMBER}
