spring:
  application:
    name: speaker-reminders
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: ${MAIL_PROTOCOL}
  batch:
    job:
      enabled: false
  main:
    allow-bean-definition-overriding: true

  mvc:
    servlet:
      path: /api

google:
  sheet: ${GSHEET_BOOK}
  speaker-sheet: ${GSHEET_SPEAKER}

email:
  from: ${EMAIL_FROM}
  cc: ${EMAIL_CC}

video-dept:
  email: ${VIDEO_DEPT_EMAIL}
  overseer-name: ${VIDEO_DEPT_OVERSEER_NAME}
  overseer-phone: ${VIDEO_DEPT_OVERSEER_PHONE}

cron:
  schedule: ${CRON_EXPRESSION}

whatsapp:
  url: ${WHATSAPP_URL}
  template:
    first: ${WHATSAPP_TEMPLATE_FIRST}
    second: ${WHATSAPP_TEMPLATE_SECOND}
  token: ${WHATSAPP_TOKEN}
  phoneNumberId: ${WHATSAPP_PHONE_NUMBER_ID}
  testPhoneNumber: ${WHATSAPP_TEST_PHONE_NUMBER}

server:
  port: ${TOMCAT_PORT:8080}
