spring:
  application:
    name: speaker-reminders

  profiles:
    include:
      - ${ENVIRONMENT_PROFILE:dev}

  batch:
    job:
      enabled: false
  main:
    allow-bean-definition-overriding: true

  mvc:
    servlet:
      path: /api

google:
  sheet: ${GSHEET_BOOK}
  speaker-sheet: ${GSHEET_SPEAKER}

email:
  from: ${EMAIL_FROM}
  cc: ${EMAIL_CC}

video-dept:
  email: ${VIDEO_DEPT_EMAIL}
  overseer-name: ${VIDEO_DEPT_OVERSEER_NAME}
  overseer-phone: ${VIDEO_DEPT_OVERSEER_PHONE}

cron:
  schedule: ${CRON_EXPRESSION}

whatsapp:
  url: ${WHATSAPP_URL}
  template:
    first: ${WHATSAPP_TEMPLATE_FIRST}
    second: ${WHATSAPP_TEMPLATE_SECOND}
  token: ${WHATSAPP_TOKEN}
  phoneNumberId: ${WHATSAPP_PHONE_NUMBER_ID}
  testPhoneNumber: ${WHATSAPP_TEST_PHONE_NUMBER}

server:
  port: ${TOMCAT_PORT:8080}
